import { useEffect, useState } from 'react';
import { ArrowDownAZ, Package, Search } from 'lucide-react';
import { api } from '../services/api';

export default function Pharmacy({ user }) {
  const [items, setItems] = useState([]); const [expiryFirst, setExpiryFirst] = useState(true); const [search, setSearch] = useState(''); const [message, setMessage] = useState('');
  async function load() { try { setItems(await api(`${expiryFirst ? '/pharmacy/products-expiry-first' : '/pharmacy/products'}?search=${encodeURIComponent(search)}`)); } catch (error) { setMessage(error.message); } }
  useEffect(() => { load(); }, [expiryFirst]);
  return <><div className="page-toolbar"><div><p className="eyebrow">{user.role === 'PHARMACY' ? 'PHARMACY BILLING' : 'PHARMACY CONTROL'}</p><p className="lede">{expiryFirst ? 'Earliest-expiring batches are shown first.' : 'Products sorted alphabetically.'}</p></div><div className="pharmacy-actions"><div className="search compact-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Search products" /></div><button className={expiryFirst ? 'secondary active-filter' : 'secondary'} onClick={() => setExpiryFirst(!expiryFirst)}><ArrowDownAZ size={16} /> Expiry first</button></div></div>{message && <div className="alert error">{message}</div>}<section className="product-grid">{items.map((product) => { const batch = product.batches[0]; const expired = batch && new Date(batch.expiryDate) <= new Date(); return <article className="product-card" key={product.id}><div className="product-top"><div className="product-icon"><Package size={20} /></div><span className={expired ? 'tag warning' : batch?.quantity <= product.reorderLevel ? 'tag warning' : 'tag'}>{expired ? 'Expired' : batch?.quantity <= product.reorderLevel ? 'Low stock' : 'In stock'}</span></div><h3>{product.name}</h3><p className="muted">{product.genericName || 'General medicine'} · Batch {batch?.batchNumber}</p><div className="product-meta"><span><strong>{batch?.quantity ?? 0}</strong> units</span><span>Expires {batch ? new Date(batch.expiryDate).toLocaleDateString() : '—'}</span></div></article>; })}</section></>;
}
