import { useEffect, useState } from 'react';
import { Edit3, Plus, Save } from 'lucide-react';
import { api } from '../services/api';
import './ReferenceAgents.css';

export default function ReferenceAgents({ user }) {
  const [agents, setAgents] = useState([]); const [form, setForm] = useState({ name: '', phone: '', occupation: '', commissionPercent: 0 }); const [message, setMessage] = useState(''); const [editing, setEditing] = useState(null);
  async function load() { setAgents(await api('/reference-agents')); }
  useEffect(() => { load().catch((error) => setMessage(error.message)); }, []);
  async function submit(event) { event.preventDefault(); try { await api('/reference-agents', { method: 'POST', body: JSON.stringify(form) }); setMessage('Reference agent added.'); setForm({ name: '', phone: '', occupation: '', commissionPercent: 0 }); await load(); } catch (error) { setMessage(error.message); } }
  async function saveCommission(agent) { try { await api(`/reference-agents/${agent.id}`, { method: 'PATCH', body: JSON.stringify({ commissionPercent: Number(agent.commissionPercent) }) }); setEditing(null); setMessage('Commission percentage updated by Admin.'); await load(); } catch (error) { setMessage(error.message); } }
  return <><div className="page-toolbar"><div><p className="eyebrow">REFERENCE DESK</p><p className="lede">Reception can add referral contacts. Only Admin controls commission percentage.</p></div></div>{message && <div className="alert">{message}</div>}<form className="panel form-panel" onSubmit={submit}><div className="form-grid">{[['name','Reference person name'],['phone','Phone number'],['occupation','Occupation']].map(([key, label]) => <label key={key}>{label}<input required={key !== 'occupation'} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}{user.role === 'ADMIN' && <label>Commission percentage<input type="number" min="0" max="100" step="0.01" value={form.commissionPercent} onChange={(event) => setForm({ ...form, commissionPercent: event.target.value })} /></label>}</div><button className="primary"><Plus size={16} /> Add reference person</button></form><section className="panel table-panel"><table><thead><tr><th>Name</th><th>Phone</th><th>Occupation</th><th>Commission</th><th>Action</th></tr></thead><tbody>{agents.map((agent) => <tr key={agent.id}><td><strong>{agent.name}</strong></td><td>{agent.phone}</td><td>{agent.occupation || '—'}</td><td>{editing === agent.id ? <input className="inline-input" type="number" min="0" max="100" step="0.01" value={agent.commissionPercent} onChange={(event) => setAgents(agents.map((item) => item.id === agent.id ? { ...item, commissionPercent: event.target.value } : item))} /> : `${agent.commissionPercent}%`}</td><td>{user.role === 'ADMIN' && (editing === agent.id ? <button className="icon-button" title="Save commission" onClick={() => saveCommission(agent)}><Save size={16} /></button> : <button className="icon-button" title="Edit commission" onClick={() => setEditing(agent.id)}><Edit3 size={16} /></button>)}</td></tr>)}{!agents.length && <tr><td colSpan="5" className="empty">No reference agents added.</td></tr>}</tbody></table></section></>;
}
