import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { PrismaClient } from '@prisma/client';
import { body, validationResult } from 'express-validator';
import { authenticate, authorize } from './middleware/auth.js';

export const prisma = new PrismaClient();
export const app = express();
const allowedOrigins = [
  'http://localhost:5173',
  'http://localhost:3000',
  'https://abhitcare.cloud',
  'https://www.abhitcare.cloud',
  ...(process.env.CORS_ORIGIN || '').split(',').map((origin) => origin.trim()).filter(Boolean)
];
if (process.env.NODE_ENV === 'production' && (!process.env.CORS_ORIGIN || process.env.JWT_SECRET?.length < 32)) throw new Error('CORS_ORIGIN and a 32-character JWT_SECRET are required in production');
app.set('trust proxy', process.env.TRUST_PROXY === 'true');
app.use(helmet({ contentSecurityPolicy: process.env.NODE_ENV === 'production' ? undefined : false }));
app.use(cors({
  origin: (origin, callback) => {
    const localDevOrigin = process.env.NODE_ENV !== 'production' && /^https?:\/\/(localhost|127\.0\.0\.1):51\d{2}$/.test(origin || '');
    return !origin || allowedOrigins.includes(origin) || localDevOrigin ? callback(null, true) : callback(new Error('Origin is not allowed by CORS'));
  },
  credentials: true
}));
app.use(express.json({ limit: '1mb' }));
app.use(morgan('dev'));
app.use((req, _res, next) => { if (!req.path.startsWith('/api/')) req.url = `/api${req.url}`; next(); });
const validate = (req, res, next) => { const errors = validationResult(req); return errors.isEmpty() ? next() : res.status(400).json({ message: errors.array()[0].msg }); };
const audit = async (userId, action, entity, entityId) => { try { await prisma.auditLog.create({ data: { userId, action, entity, entityId: String(entityId ?? '') } }); } catch (error) { console.error('Audit log write failed', error); } };
const patientInclude = { department: true };
const loginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: 'draft-7', legacyHeaders: false, message: { message: 'Too many login attempts. Try again later.' } });

app.get('/api/health', (_req, res) => res.json({ status: 'ok', service: 'HMS API' }));
app.get('/api/ready', async (_req, res) => { try { await prisma.$queryRaw`SELECT 1`; res.json({ status: 'ready', database: 'ok' }); } catch { res.status(503).json({ status: 'not_ready', database: 'unavailable' }); } });
app.post('/api/auth/login', loginLimiter, [body('email').trim().notEmpty().withMessage('Username or email is required'), body('password').isLength({ min: 8 }).withMessage('Password must be at least 8 characters')], validate, async (req, res, next) => {
  try {
    const identifier = req.body.email.toLowerCase();
    const user = await prisma.user.findFirst({ where: { OR: [{ email: identifier }, { username: identifier }] }, include: { doctor: true } });
    if (!user || !(await bcrypt.compare(req.body.password, user.passwordHash))) return res.status(401).json({ message: 'Invalid email or password' });
    const token = jwt.sign({ userId: user.id, role: user.role }, process.env.JWT_SECRET, { expiresIn: '8h' });
    await audit(user.id, 'LOGIN', 'User', user.id);
    res.json({ token, user: { id: user.id, name: user.name, email: user.email, role: user.role, doctorId: user.doctor?.id } });
  } catch (error) { next(error); }
});
app.get('/api/auth/me', authenticate, (req, res) => res.json({ id: req.user.id, name: req.user.name, email: req.user.email, role: req.user.role }));
app.post('/api/auth/logout', authenticate, async (req, res) => { await audit(req.user.id, 'LOGOUT', 'User', req.user.id); res.json({ message: 'Logged out' }); });

app.get('/api/dashboard', authenticate, async (req, res, next) => {
  try {
    const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1);
    const [patients, appointments, doctors, pendingLabs, pendingInvoices, products] = await Promise.all([
      prisma.patient.count(), prisma.appointment.count({ where: { appointmentDate: { gte: start, lt: end } } }), prisma.doctor.count({ where: { active: true } }), prisma.labOrder.count({ where: { status: { not: 'COMPLETED' } } }), prisma.invoice.count({ where: { status: { not: 'PAID' } } }), prisma.pharmacyBatch.findMany({ include: { product: true } })
    ]);
    const stock = products.reduce((sum, batch) => sum + batch.quantity, 0); const lowStock = products.filter((batch) => batch.quantity <= batch.product.reorderLevel).length;
    res.json({ patients, appointments, doctors, pendingLabs, pendingInvoices, stock, lowStock, role: req.user.role });
  } catch (error) { next(error); }
});

app.get('/api/patients', authenticate, async (req, res, next) => { try { const q = req.query.search || ''; const patients = await prisma.patient.findMany({ where: { OR: [{ patientNumber: { contains: q } }, { firstName: { contains: q } }, { lastName: { contains: q } }, { mobile: { contains: q } }, { email: { contains: q } }] }, include: patientInclude, orderBy: { createdAt: 'desc' }, take: 100 }); res.json(patients); } catch (error) { next(error); } });
app.get('/api/patients/:id', authenticate, async (req, res, next) => { try { const patient = await prisma.patient.findUnique({ where: { id: Number(req.params.id) }, include: { ...patientInclude, outpatientVisits: { include: { doctor: true }, orderBy: { createdAt: 'desc' } }, appointments: { include: { doctor: true }, orderBy: { appointmentDate: 'desc' } }, consultations: { orderBy: { createdAt: 'desc' } }, prescriptions: { include: { items: true }, orderBy: { createdAt: 'desc' } }, labOrders: { include: { items: { include: { labTest: true, result: true } } }, orderBy: { createdAt: 'desc' } } } }); if (!patient) return res.status(404).json({ message: 'Patient not found' }); res.json(patient); } catch (error) { next(error); } });
app.get('/api/patients/:id/financial-summary', authenticate, authorize('ADMIN', 'RECEPTION', 'DOCTOR', 'LAB', 'PHARMACY'), async (req, res, next) => { try { const [patient, invoices, pharmacySales, labOrders] = await Promise.all([prisma.patient.findUnique({ where: { id: Number(req.params.id) }, include: { outpatientVisits: { orderBy: { createdAt: 'desc' }, take: 20 } } }), prisma.invoice.findMany({ where: { patientId: Number(req.params.id) }, include: { payments: true }, orderBy: { createdAt: 'desc' } }), prisma.pharmacySale.findMany({ where: { patientId: Number(req.params.id) }, orderBy: { createdAt: 'desc' }, take: 20 }), prisma.labOrder.findMany({ where: { patientId: Number(req.params.id), status: { not: 'COMPLETED' } }, include: { items: { include: { labTest: true } } } })]); if (!patient) return res.status(404).json({ message: 'Patient not found' }); const outpatientDue = patient.outpatientVisits.reduce((sum, visit) => sum + Number(visit.balanceAmount || 0), 0); const invoiceDue = invoices.reduce((sum, invoice) => sum + Math.max(0, invoice.total - invoice.paid), 0); res.json({ patientId: patient.id, patientNumber: patient.patientNumber, outpatientVisits: patient.outpatientVisits, invoices, pharmacySales, pendingLabOrders: labOrders, totals: { outpatientDue, invoiceDue, totalDue: outpatientDue + invoiceDue, pharmacyPaid: pharmacySales.reduce((sum, sale) => sum + sale.total, 0), pendingLabCount: labOrders.length } }); } catch (error) { next(error); } });
app.post('/api/patients', authenticate, authorize('ADMIN', 'RECEPTION'), [body('firstName').trim().notEmpty(), body('mobile').trim().notEmpty(), body('gender').notEmpty()], validate, async (req, res, next) => { try { const count = await prisma.patient.count(); const patientNumber = `PAT-${new Date().getFullYear()}-${String(count + 1).padStart(6, '0')}`; const patientData = { registrationType: req.body.registrationType, firstName: req.body.firstName, lastName: req.body.lastName, mobile: req.body.mobile, email: req.body.email, gender: req.body.gender, title: req.body.title, dateOfBirth: req.body.dateOfBirth ? new Date(req.body.dateOfBirth) : undefined, age: req.body.age ? Number(req.body.age) : undefined, bloodGroup: req.body.bloodGroup, maritalStatus: req.body.maritalStatus, aadhaarNumber: req.body.aadhaarNumber, abhaNumber: req.body.abhaNumber, isMlc: Boolean(req.body.isMlc), occupation: req.body.occupation, countryCode: req.body.countryCode, address: req.body.address, city: req.body.city, state: req.body.state, locality: req.body.locality, pinCode: req.body.pinCode, guardianName: req.body.guardianName, motherName: req.body.motherName, guardianRelationship: req.body.guardianRelationship, guardianMobile: req.body.guardianMobile, symptoms: req.body.symptoms, allergies: req.body.allergies, medicalConditions: req.body.medicalConditions, emergencyContactName: req.body.emergencyContactName, emergencyContactNumber: req.body.emergencyContactNumber, photoPath: req.body.photoPath, departmentId: req.body.departmentId ? Number(req.body.departmentId) : undefined, referenceAgentId: req.body.referenceAgentId ? Number(req.body.referenceAgentId) : undefined, patientNumber }; const patient = await prisma.patient.create({ data: patientData }); await audit(req.user.id, 'PATIENT_CREATED', 'Patient', patient.id); res.status(201).json(patient); } catch (error) { next(error); } });
app.post('/api/outpatient-visits', authenticate, authorize('ADMIN', 'RECEPTION'), [body('patientId').isInt({ min: 1 }), body('visitType').trim().notEmpty(), body('paymentMode').isIn(['CASH', 'CARD', 'UPI', 'INSURANCE', 'OTHER']), body('consultationFee').optional().isFloat({ min: 0 }), body('registrationFee').optional().isFloat({ min: 0 }), body('discountAmount').optional().isFloat({ min: 0 })], validate, async (req, res, next) => { try { const patient = await prisma.patient.findUnique({ where: { id: Number(req.body.patientId) } }); if (!patient) return res.status(404).json({ message: 'Patient not found' }); const consultationFee = Number(req.body.consultationFee || 0); const registrationFee = Number(req.body.registrationFee || 0); const discountAmount = Number(req.body.discountAmount || 0); const total = consultationFee + registrationFee; if (discountAmount > total) return res.status(400).json({ message: 'Discount cannot exceed the OP total' }); const visit = await prisma.$transaction(async (tx) => { const created = await tx.outpatientVisit.create({ data: { patientId: patient.id, doctorId: req.body.doctorId ? Number(req.body.doctorId) : undefined, visitType: req.body.visitType, referralType: req.body.referralType, appointmentDate: req.body.appointmentDate ? new Date(req.body.appointmentDate) : undefined, appointmentTime: req.body.appointmentTime, consultationFee, registrationFee, paymentMode: req.body.paymentMode, discount: Number(req.body.discount || 0), discountAmount, finalAmount: total - discountAmount } }); if (req.body.doctorId && req.body.appointmentDate && req.body.appointmentTime) await tx.appointment.create({ data: { patientId: patient.id, doctorId: Number(req.body.doctorId), departmentId: req.body.departmentId ? Number(req.body.departmentId) : undefined, appointmentDate: new Date(req.body.appointmentDate), appointmentTime: req.body.appointmentTime, reason: req.body.visitType } }); return created; }); await audit(req.user.id, 'OUTPATIENT_VISIT_CREATED', 'OutpatientVisit', visit.id); res.status(201).json(visit); } catch (error) { if (error.code === 'P2002') return res.status(409).json({ message: 'That appointment slot is already booked' }); next(error); } });
app.patch('/api/outpatient-visits/:id/payment', authenticate, authorize('ADMIN', 'RECEPTION'), [body('paidAmount').isFloat({ min: 0 })], validate, async (req, res, next) => { try { const visit = await prisma.outpatientVisit.findUnique({ where: { id: Number(req.params.id) } }); if (!visit) return res.status(404).json({ message: 'Outpatient visit not found' }); const paidAmount = Number(req.body.paidAmount); if (paidAmount > visit.finalAmount) return res.status(400).json({ message: 'Paid amount cannot exceed final amount' }); const updated = await prisma.outpatientVisit.update({ where: { id: visit.id }, data: { paidAmount, balanceAmount: visit.finalAmount - paidAmount } }); await audit(req.user.id, 'OUTPATIENT_PAYMENT_RECORDED', 'OutpatientVisit', visit.id); res.json(updated); } catch (error) { next(error); } });
app.get('/api/reference-agents', authenticate, authorize('ADMIN', 'RECEPTION'), async (_req, res, next) => { try { res.json(await prisma.referenceAgent.findMany({ where: { active: true }, orderBy: { name: 'asc' } })); } catch (error) { next(error); } });
app.post('/api/reference-agents', authenticate, authorize('ADMIN', 'RECEPTION'), [body('name').trim().notEmpty(), body('phone').trim().notEmpty(), body('occupation').optional().trim().isLength({ max: 100 }), body('commissionPercent').optional().isFloat({ min: 0, max: 100 })], validate, async (req, res, next) => { try { const agent = await prisma.referenceAgent.create({ data: { name: req.body.name, phone: req.body.phone, occupation: req.body.occupation, commissionPercent: req.user.role === 'ADMIN' ? Number(req.body.commissionPercent || 0) : 0 } }); await audit(req.user.id, 'REFERENCE_AGENT_CREATED', 'ReferenceAgent', agent.id); res.status(201).json(agent); } catch (error) { next(error); } });
app.patch('/api/reference-agents/:id', authenticate, authorize('ADMIN'), [body('commissionPercent').optional().isFloat({ min: 0, max: 100 }), body('active').optional().isBoolean()], validate, async (req, res, next) => { try { const agent = await prisma.referenceAgent.update({ where: { id: Number(req.params.id) }, data: { commissionPercent: req.body.commissionPercent === undefined ? undefined : Number(req.body.commissionPercent), active: req.body.active === undefined ? undefined : req.body.active } }); await audit(req.user.id, 'REFERENCE_AGENT_UPDATED', 'ReferenceAgent', agent.id); res.json(agent); } catch (error) { next(error); } });
app.get('/api/departments', authenticate, async (_req, res, next) => { try { res.json(await prisma.department.findMany({ orderBy: { name: 'asc' } })); } catch (error) { next(error); } });
app.get('/api/doctors', authenticate, async (_req, res, next) => { try { res.json(await prisma.doctor.findMany({ where: { active: true }, include: { department: true }, orderBy: { name: 'asc' } })); } catch (error) { next(error); } });
app.post('/api/doctors', authenticate, authorize('ADMIN'), [body('name').trim().notEmpty(), body('email').isEmail(), body('temporaryPassword').isLength({ min: 12 }).withMessage('Temporary password must be at least 12 characters')], validate, async (req, res, next) => { try { const passwordHash = await bcrypt.hash(req.body.temporaryPassword, 12); const user = await prisma.user.create({ data: { name: req.body.name, email: req.body.email.toLowerCase(), passwordHash, role: 'DOCTOR' } }); const doctor = await prisma.doctor.create({ data: { userId: user.id, name: req.body.name, qualification: req.body.qualification, specialization: req.body.specialization, departmentId: req.body.departmentId ? Number(req.body.departmentId) : undefined, consultationFee: Number(req.body.consultationFee || 0), phone: req.body.phone, email: user.email } }); await audit(req.user.id, 'DOCTOR_CREATED', 'Doctor', doctor.id); res.status(201).json(doctor); } catch (error) { if (error.code === 'P2002') return res.status(409).json({ message: 'Email already exists' }); next(error); } });
app.patch('/api/doctors/:id', authenticate, authorize('ADMIN'), [body('consultationFee').optional().isFloat({ min: 0, max: 100000000 }), body('active').optional().isBoolean()], validate, async (req, res, next) => { try { const doctor = await prisma.doctor.update({ where: { id: Number(req.params.id) }, data: { consultationFee: req.body.consultationFee === undefined ? undefined : Number(req.body.consultationFee), active: req.body.active === undefined ? undefined : req.body.active } }); await audit(req.user.id, 'DOCTOR_UPDATED', 'Doctor', doctor.id); res.json(doctor); } catch (error) { next(error); } });

app.get('/api/appointments', authenticate, async (req, res, next) => { try { const where = req.user.role === 'DOCTOR' ? { doctor: { userId: req.user.id } } : {}; res.json(await prisma.appointment.findMany({ where, include: { patient: true, doctor: true, department: true }, orderBy: [{ appointmentDate: 'desc' }, { appointmentTime: 'asc' }] })); } catch (error) { next(error); } });
app.post('/api/appointments', authenticate, authorize('ADMIN', 'RECEPTION'), [body('patientId').isInt({ min: 1 }), body('doctorId').isInt({ min: 1 }), body('appointmentDate').isISO8601(), body('appointmentTime').matches(/^([01]\d|2[0-3]):[0-5]\d$/).withMessage('Time must use HH:MM format')], validate, async (req, res, next) => { try { const date = new Date(req.body.appointmentDate); const existing = await prisma.appointment.findFirst({ where: { doctorId: Number(req.body.doctorId), appointmentDate: date, appointmentTime: req.body.appointmentTime, status: { not: 'CANCELLED' } } }); if (existing) return res.status(409).json({ message: 'This doctor is already booked for that time' }); const appointment = await prisma.appointment.create({ data: { patientId: Number(req.body.patientId), doctorId: Number(req.body.doctorId), departmentId: req.body.departmentId ? Number(req.body.departmentId) : undefined, appointmentDate: date, appointmentTime: req.body.appointmentTime, reason: req.body.reason } }); res.status(201).json(appointment); } catch (error) { if (error.code === 'P2002') return res.status(409).json({ message: 'This doctor is already booked for that time' }); next(error); } });
app.patch('/api/appointments/:id/status', authenticate, authorize('ADMIN', 'DOCTOR', 'RECEPTION'), [body('status').isIn(['SCHEDULED', 'CONFIRMED', 'WAITING', 'IN_CONSULTATION', 'COMPLETED', 'CANCELLED', 'NO_SHOW']).withMessage('Invalid appointment status')], validate, async (req, res, next) => { try { const appointment = await prisma.appointment.update({ where: { id: Number(req.params.id) }, data: { status: req.body.status } }); res.json(appointment); } catch (error) { next(error); } });

app.get('/api/pharmacy/products', authenticate, async (req, res, next) => { try { res.json(await prisma.pharmacyProduct.findMany({ where: { status: 'ACTIVE', name: { contains: req.query.search || '' } }, include: { batches: { orderBy: { expiryDate: 'asc' } } }, orderBy: { name: 'asc' } })); } catch (error) { next(error); } });
app.get('/api/pharmacy/products-expiry-first', authenticate, async (req, res, next) => { try { const products = await prisma.pharmacyProduct.findMany({ where: { status: 'ACTIVE', name: { contains: req.query.search || '' } }, include: { batches: { orderBy: { expiryDate: 'asc' } } } }); products.sort((left, right) => new Date(left.batches[0]?.expiryDate || '2999-12-31') - new Date(right.batches[0]?.expiryDate || '2999-12-31')); res.json(products); } catch (error) { next(error); } });
app.post('/api/pharmacy/products', authenticate, authorize('ADMIN'), [body('name').trim().notEmpty(), body('batchNumber').trim().notEmpty(), body('quantity').isInt({ min: 0, max: 100000 }), body('sellingPrice').isFloat({ min: 0, max: 100000000 }), body('purchasePrice').optional().isFloat({ min: 0, max: 100000000 }), body('taxPercentage').optional().isFloat({ min: 0, max: 100 }), body('expiryDate').isISO8601().custom((value) => new Date(value) > new Date()).withMessage('Expiry must be a future date')], validate, async (req, res, next) => { try { const result = await prisma.$transaction(async (tx) => { const product = await tx.pharmacyProduct.create({ data: { name: req.body.name, genericName: req.body.genericName, category: req.body.category, manufacturer: req.body.manufacturer, sku: req.body.sku, reorderLevel: Number(req.body.reorderLevel || 10) } }); const batch = await tx.pharmacyBatch.create({ data: { productId: product.id, batchNumber: req.body.batchNumber, expiryDate: new Date(req.body.expiryDate), quantity: Number(req.body.quantity), purchasePrice: Number(req.body.purchasePrice || 0), sellingPrice: Number(req.body.sellingPrice), taxPercentage: Number(req.body.taxPercentage || 0), supplier: req.body.supplier } }); return { ...product, batches: [batch] }; }); await audit(req.user.id, 'PRODUCT_CREATED', 'PharmacyProduct', result.id); res.status(201).json(result); } catch (error) { if (error.code === 'P2002') return res.status(409).json({ message: 'SKU or batch already exists' }); next(error); } });
app.patch('/api/pharmacy/products/:id', authenticate, authorize('ADMIN'), async (req, res, next) => { try { const product = await prisma.pharmacyProduct.update({ where: { id: Number(req.params.id) }, data: { name: req.body.name, reorderLevel: req.body.reorderLevel ? Number(req.body.reorderLevel) : undefined, status: req.body.status } }); res.json(product); } catch (error) { next(error); } });
app.post('/api/pharmacy/sales', authenticate, authorize('ADMIN', 'RECEPTION', 'PHARMACY'), [body('items').isArray({ min: 1 }), body('items.*.batchId').isInt({ min: 1 }), body('items.*.quantity').isInt({ min: 1, max: 100000 }), body('paymentMode').isIn(['CASH', 'CARD', 'UPI', 'INSURANCE', 'OTHER']), body('discount').optional().isFloat({ min: 0, max: 100000000 })], validate, async (req, res, next) => { try { const sale = await prisma.$transaction(async (tx) => { let subtotal = 0; let tax = 0; const items = []; for (const item of req.body.items) { const batch = await tx.pharmacyBatch.findUnique({ where: { id: Number(item.batchId) }, include: { product: true } }); if (!batch || batch.product.status !== 'ACTIVE') throw Object.assign(new Error('Product not found'), { status: 404 }); if (batch.expiryDate <= new Date()) throw Object.assign(new Error(`Expired Product: ${batch.product.name}`), { status: 400 }); if (batch.quantity < Number(item.quantity)) throw Object.assign(new Error(`Insufficient stock for ${batch.product.name}`), { status: 400 }); const line = batch.sellingPrice * Number(item.quantity); const lineTax = line * batch.taxPercentage / 100; subtotal += line; tax += lineTax; items.push({ productId: batch.productId, batchId: batch.id, quantity: Number(item.quantity), unitPrice: batch.sellingPrice, tax: lineTax }); await tx.pharmacyBatch.update({ where: { id: batch.id }, data: { quantity: { decrement: Number(item.quantity) } } }); } const discount = Number(req.body.discount || 0); if (discount > subtotal + tax) throw Object.assign(new Error('Discount cannot exceed sale total'), { status: 400 }); return tx.pharmacySale.create({ data: { patientId: req.body.patientId ? Number(req.body.patientId) : undefined, subtotal, tax, discount, total: subtotal + tax - discount, paymentMode: req.body.paymentMode, items: { create: items } }, include: { items: { include: { product: true, batch: true } }, patient: true } }); }); await audit(req.user.id, 'PHARMACY_SALE', 'PharmacySale', sale.id); res.status(201).json(sale); } catch (error) { res.status(error.status || 500).json({ message: error.status ? error.message : 'Unable to complete pharmacy sale' }); } });
app.get('/api/pharmacy/sales', authenticate, authorize('ADMIN', 'RECEPTION', 'PHARMACY'), async (_req, res, next) => { try { res.json(await prisma.pharmacySale.findMany({ include: { patient: true, items: { include: { product: true, batch: true } } }, orderBy: { createdAt: 'desc' }, take: 100 })); } catch (error) { next(error); } });

app.get('/api/lab/tests', authenticate, async (_req, res, next) => { try { res.json(await prisma.labTest.findMany({ where: { active: true }, include: { department: true }, orderBy: { name: 'asc' } })); } catch (error) { next(error); } });
app.get('/api/lab/orders', authenticate, async (req, res, next) => { try { const where = req.user.role === 'DOCTOR' ? { orderedById: req.user.id } : {}; res.json(await prisma.labOrder.findMany({ where, include: { patient: true, orderedBy: true, items: { include: { labTest: true, result: true } } }, orderBy: { createdAt: 'desc' } })); } catch (error) { next(error); } });
app.post('/api/lab/orders', authenticate, authorize('ADMIN', 'DOCTOR'), [body('patientId').isInt(), body('testIds').isArray({ min: 1 })], validate, async (req, res, next) => { try { const order = await prisma.labOrder.create({ data: { patientId: Number(req.body.patientId), orderedById: req.user.id, consultationId: req.body.consultationId ? Number(req.body.consultationId) : undefined, items: { create: req.body.testIds.map((id) => ({ labTestId: Number(id) })) } }, include: { items: { include: { labTest: true } }, patient: true } }); await audit(req.user.id, 'LAB_ORDER_CREATED', 'LabOrder', order.id); res.status(201).json(order); } catch (error) { next(error); } });
app.patch('/api/lab/orders/:id/status', authenticate, authorize('ADMIN', 'LAB'), async (req, res, next) => { try { const order = await prisma.labOrder.update({ where: { id: Number(req.params.id) }, data: { status: req.body.status, technicianNotes: req.body.technicianNotes } }); res.json(order); } catch (error) { next(error); } });
app.post('/api/lab/results', authenticate, authorize('ADMIN', 'LAB'), [body('orderItemId').isInt(), body('result').notEmpty()], validate, async (req, res, next) => { try { const result = await prisma.labResult.upsert({ where: { orderItemId: Number(req.body.orderItemId) }, update: { result: req.body.result, unit: req.body.unit, remarks: req.body.remarks, completedAt: new Date() }, create: { orderItemId: Number(req.body.orderItemId), result: req.body.result, unit: req.body.unit, normalRange: req.body.normalRange, remarks: req.body.remarks, sampleDate: new Date(), completedAt: new Date() } }); res.status(201).json(result); } catch (error) { next(error); } });

app.post('/api/consultations', authenticate, authorize('ADMIN', 'DOCTOR'), [body('patientId').isInt(), body('doctorId').isInt()], validate, async (req, res, next) => { try { const consultation = await prisma.consultation.create({ data: { patientId: Number(req.body.patientId), doctorId: Number(req.body.doctorId), appointmentId: req.body.appointmentId ? Number(req.body.appointmentId) : undefined, chiefComplaint: req.body.chiefComplaint, symptoms: req.body.symptoms, diagnosis: req.body.diagnosis, examinationNotes: req.body.examinationNotes, treatmentPlan: req.body.treatmentPlan, doctorNotes: req.body.doctorNotes, followUpDate: req.body.followUpDate ? new Date(req.body.followUpDate) : undefined } }); if (req.body.appointmentId) await prisma.appointment.update({ where: { id: Number(req.body.appointmentId) }, data: { status: 'COMPLETED' } }); await audit(req.user.id, 'CONSULTATION_CREATED', 'Consultation', consultation.id); res.status(201).json(consultation); } catch (error) { next(error); } });
app.post('/api/prescriptions', authenticate, authorize('ADMIN', 'DOCTOR'), [body('patientId').isInt(), body('doctorId').isInt(), body('items').isArray({ min: 1 })], validate, async (req, res, next) => { try { const prescription = await prisma.prescription.create({ data: { patientId: Number(req.body.patientId), doctorId: Number(req.body.doctorId), consultationId: req.body.consultationId ? Number(req.body.consultationId) : undefined, diagnosis: req.body.diagnosis, items: { create: req.body.items.map((item) => ({ productId: item.productId ? Number(item.productId) : undefined, medicineName: item.medicineName, dosage: item.dosage, frequency: item.frequency, duration: item.duration, route: item.route, instructions: item.instructions })) } }, include: { items: true } }); await audit(req.user.id, 'PRESCRIPTION_CREATED', 'Prescription', prescription.id); res.status(201).json(prescription); } catch (error) { next(error); } });

app.get('/api/billing/invoices', authenticate, async (req, res, next) => { try { const invoices = await prisma.invoice.findMany({ where: req.query.patientId ? { patientId: Number(req.query.patientId) } : {}, include: { patient: true, items: true, payments: true }, orderBy: { createdAt: 'desc' } }); res.json(invoices); } catch (error) { next(error); } });
app.post('/api/billing/invoices-with-reference', authenticate, authorize('ADMIN', 'RECEPTION'), [body('patientId').isInt(), body('items').isArray({ min: 1 }), body('referenceAgentId').optional().isInt(), body('discount').optional().isFloat({ min: 0 }), body('tax').optional().isFloat({ min: 0 })], validate, async (req, res, next) => { try { const subtotal = req.body.items.reduce((sum, item) => sum + Number(item.quantity || 1) * Number(item.unitPrice), 0); const discount = Number(req.body.discount || 0); const tax = Number(req.body.tax || 0); const agent = req.body.referenceAgentId ? await prisma.referenceAgent.findFirst({ where: { id: Number(req.body.referenceAgentId), active: true } }) : null; if (req.body.referenceAgentId && !agent) return res.status(404).json({ message: 'Reference agent not found' }); const commissionPercent = agent?.commissionPercent || 0; const total = subtotal + tax - discount; const invoice = await prisma.invoice.create({ data: { invoiceNumber: `INV-${Date.now()}`, patientId: Number(req.body.patientId), referenceAgentId: agent?.id, commissionPercent, commissionAmount: total * commissionPercent / 100, subtotal, discount, tax, total, items: { create: req.body.items.map((item) => ({ description: item.description, category: item.category || 'Other', quantity: Number(item.quantity || 1), unitPrice: Number(item.unitPrice) })) } }, include: { items: true, patient: true, referenceAgent: true } }); await audit(req.user.id, 'INVOICE_CREATED', 'Invoice', invoice.id); res.status(201).json(invoice); } catch (error) { next(error); } });
app.post('/api/billing/invoices', authenticate, authorize('ADMIN', 'RECEPTION'), [body('patientId').isInt(), body('items').isArray({ min: 1 })], validate, async (req, res, next) => { try { const subtotal = req.body.items.reduce((sum, item) => sum + Number(item.quantity || 1) * Number(item.unitPrice), 0); const discount = Number(req.body.discount || 0); const tax = Number(req.body.tax || 0); const invoice = await prisma.invoice.create({ data: { invoiceNumber: `INV-${Date.now()}`, patientId: Number(req.body.patientId), subtotal, discount, tax, total: subtotal + tax - discount, items: { create: req.body.items.map((item) => ({ description: item.description, category: item.category || 'Other', quantity: Number(item.quantity || 1), unitPrice: Number(item.unitPrice) })) } }, include: { items: true, patient: true } }); await audit(req.user.id, 'INVOICE_CREATED', 'Invoice', invoice.id); res.status(201).json(invoice); } catch (error) { next(error); } });
app.post('/api/billing/invoices/:id/payments', authenticate, authorize('ADMIN', 'RECEPTION'), [body('amount').isFloat({ min: 0 }), body('mode').isIn(['CASH', 'CARD', 'UPI', 'INSURANCE', 'OTHER'])], validate, async (req, res, next) => { try { const invoice = await prisma.$transaction(async (tx) => { const current = await tx.invoice.findUnique({ where: { id: Number(req.params.id) } }); if (!current) throw Object.assign(new Error('Invoice not found'), { status: 404 }); const paid = current.paid + Number(req.body.amount); if (paid > current.total) throw Object.assign(new Error('Payment exceeds due amount'), { status: 400 }); await tx.payment.create({ data: { invoiceId: current.id, amount: Number(req.body.amount), mode: req.body.mode, reference: req.body.reference } }); return tx.invoice.update({ where: { id: current.id }, data: { paid, status: paid === current.total ? 'PAID' : 'PARTIAL' }, include: { payments: true } }); }); await audit(req.user.id, 'PAYMENT_RECORDED', 'Invoice', invoice.id); res.status(201).json(invoice); } catch (error) { res.status(error.status || 500).json({ message: error.status ? error.message : 'Unable to record payment' }); } });

app.get('/api/beds/available', authenticate, authorize('ADMIN', 'RECEPTION'), async (_req, res, next) => { try { res.json(await prisma.bed.findMany({ where: { status: 'AVAILABLE' }, include: { room: { include: { ward: true } } }, orderBy: [{ room: { dailyRate: 'asc' } }, { room: { number: 'asc' } }, { number: 'asc' }] })); } catch (error) { next(error); } });
app.post('/api/rooms', authenticate, authorize('ADMIN'), [body('wardName').trim().notEmpty(), body('number').trim().notEmpty(), body('roomType').trim().notEmpty(), body('dailyRate').isFloat({ min: 0 }), body('bedCount').isInt({ min: 1, max: 50 })], validate, async (req, res, next) => { try { const room = await prisma.$transaction(async (tx) => { const ward = await tx.ward.upsert({ where: { name: req.body.wardName }, update: {}, create: { name: req.body.wardName } }); const created = await tx.room.create({ data: { wardId: ward.id, number: req.body.number, roomType: req.body.roomType, dailyRate: Number(req.body.dailyRate), beds: { create: Array.from({ length: Number(req.body.bedCount) }, (_, index) => ({ number: String(index + 1) })) } }, include: { ward: true, beds: true } }); return created; }); await audit(req.user.id, 'ROOM_CREATED', 'Room', room.id); res.status(201).json(room); } catch (error) { if (error.code === 'P2002') return res.status(409).json({ message: 'That room already exists in the ward' }); next(error); } });
app.get('/api/admissions', authenticate, authorize('ADMIN', 'RECEPTION', 'DOCTOR'), async (req, res, next) => { try { res.json(await prisma.admission.findMany({ where: req.query.active === 'true' ? { status: 'ADMITTED' } : {}, include: { patient: true, doctor: true, bed: { include: { room: { include: { ward: true } } } }, roomStays: { orderBy: { startedAt: 'desc' } } }, orderBy: { admissionDate: 'desc' } })); } catch (error) { next(error); } });
app.post('/api/admissions/convert', authenticate, authorize('ADMIN', 'RECEPTION'), [body('patientId').isInt({ min: 1 }), body('bedId').isInt({ min: 1 }), body('admissionDate').optional().isISO8601(), body('referredDays').optional().isInt({ min: 1, max: 3650 }), body('doctorId').optional().isInt({ min: 1 })], validate, async (req, res, next) => { try { const admission = await prisma.$transaction(async (tx) => { const bed = await tx.bed.findUnique({ where: { id: Number(req.body.bedId) }, include: { room: true } }); if (!bed || bed.status !== 'AVAILABLE') throw Object.assign(new Error('Selected bed is not available'), { status: 409 }); const active = await tx.admission.findFirst({ where: { patientId: Number(req.body.patientId), status: 'ADMITTED' } }); if (active) throw Object.assign(new Error('Patient already has an active inpatient admission'), { status: 409 }); const created = await tx.admission.create({ data: { patientId: Number(req.body.patientId), bedId: bed.id, doctorId: req.body.doctorId ? Number(req.body.doctorId) : undefined, referredDays: req.body.referredDays ? Number(req.body.referredDays) : undefined, admissionDate: req.body.admissionDate ? new Date(req.body.admissionDate) : new Date(), attendantName: req.body.attendantName, attendantMobile: req.body.attendantMobile, roomStays: { create: { roomId: bed.roomId, bedId: bed.id, dailyRate: bed.room.dailyRate } } }, include: { patient: true, bed: { include: { room: true } }, roomStays: true } }); await tx.bed.update({ where: { id: bed.id }, data: { status: 'OCCUPIED' } }); await tx.patient.update({ where: { id: Number(req.body.patientId) }, data: { registrationType: 'INPATIENT' } }); return created; }); await audit(req.user.id, 'PATIENT_CONVERTED_TO_INPATIENT', 'Admission', admission.id); res.status(201).json(admission); } catch (error) { res.status(error.status || 500).json({ message: error.status ? error.message : 'Unable to convert patient to inpatient' }); } });
app.patch('/api/admissions/:id/room', authenticate, authorize('ADMIN', 'RECEPTION'), [body('bedId').isInt({ min: 1 })], validate, async (req, res, next) => { try { const admission = await prisma.$transaction(async (tx) => { const current = await tx.admission.findUnique({ where: { id: Number(req.params.id) }, include: { bed: true } }); const nextBed = await tx.bed.findUnique({ where: { id: Number(req.body.bedId) }, include: { room: true } }); if (!current || current.status !== 'ADMITTED') throw Object.assign(new Error('Active admission not found'), { status: 404 }); if (!nextBed || nextBed.status !== 'AVAILABLE') throw Object.assign(new Error('New bed is not available'), { status: 409 }); await tx.admissionRoomStay.updateMany({ where: { admissionId: current.id, endedAt: null }, data: { endedAt: new Date() } }); await tx.bed.update({ where: { id: current.bedId }, data: { status: 'AVAILABLE' } }); await tx.bed.update({ where: { id: nextBed.id }, data: { status: 'OCCUPIED' } }); await tx.admission.update({ where: { id: current.id }, data: { bedId: nextBed.id } }); return tx.admissionRoomStay.create({ data: { admissionId: current.id, roomId: nextBed.roomId, bedId: nextBed.id, dailyRate: nextBed.room.dailyRate } }); }); await audit(req.user.id, 'INPATIENT_ROOM_CHANGED', 'Admission', req.params.id); res.status(201).json(admission); } catch (error) { res.status(error.status || 500).json({ message: error.status ? error.message : 'Unable to change inpatient room' }); } });
app.patch('/api/admissions/:id/details', authenticate, authorize('ADMIN', 'RECEPTION'), [body('motherName').optional().trim(), body('vitals').optional().isString()], async (req, res, next) => { try { const admission = await prisma.$transaction(async (tx) => { const updated = await tx.admission.update({ where: { id: Number(req.params.id) }, data: { vitals: req.body.vitals } }); if (req.body.motherName !== undefined) await tx.patient.update({ where: { id: updated.patientId }, data: { motherName: req.body.motherName } }); return updated; }); res.json(admission); } catch (error) { next(error); } });
app.patch('/api/admissions/:id/discharge-to-outpatient', authenticate, authorize('ADMIN', 'DOCTOR', 'RECEPTION'), async (req, res, next) => { try { const result = await prisma.$transaction(async (tx) => { const admission = await tx.admission.findUnique({ where: { id: Number(req.params.id) } }); if (!admission || admission.status !== 'ADMITTED') throw Object.assign(new Error('Active admission not found'), { status: 404 }); const updated = await tx.admission.update({ where: { id: admission.id }, data: { status: 'DISCHARGED', dischargeDate: new Date(), dischargeSummary: req.body.dischargeSummary, finalDiagnosis: req.body.finalDiagnosis } }); await tx.bed.update({ where: { id: admission.bedId }, data: { status: 'AVAILABLE' } }); const patient = await tx.patient.update({ where: { id: admission.patientId }, data: { registrationType: 'OUTPATIENT' } }); return { admission: updated, patient }; }); await audit(req.user.id, 'INPATIENT_DISCHARGED_TO_OUTPATIENT', 'Admission', req.params.id); res.json(result); } catch (error) { res.status(error.status || 500).json({ message: error.status ? error.message : 'Unable to discharge patient to outpatient' }); } });
app.post('/api/admissions', authenticate, authorize('ADMIN', 'RECEPTION'), [body('patientId').isInt(), body('bedId').isInt()], validate, async (req, res, next) => { try { const admission = await prisma.$transaction(async (tx) => { const bed = await tx.bed.findUnique({ where: { id: Number(req.body.bedId) } }); if (!bed || bed.status !== 'AVAILABLE') throw Object.assign(new Error('Bed is not available'), { status: 409 }); const active = await tx.admission.findFirst({ where: { patientId: Number(req.body.patientId), status: 'ADMITTED' } }); if (active) throw Object.assign(new Error('Patient already has an active admission'), { status: 409 }); const created = await tx.admission.create({ data: { patientId: Number(req.body.patientId), bedId: bed.id, attendantName: req.body.attendantName, attendantMobile: req.body.attendantMobile } }); await tx.bed.update({ where: { id: bed.id }, data: { status: 'OCCUPIED' } }); return created; }); await audit(req.user.id, 'ADMISSION_CREATED', 'Admission', admission.id); res.status(201).json(admission); } catch (error) { res.status(error.status || 500).json({ message: error.status ? error.message : 'Unable to admit patient' }); } });
app.patch('/api/admissions/:id/discharge', authenticate, authorize('ADMIN', 'DOCTOR', 'RECEPTION'), async (req, res, next) => { try { const admission = await prisma.$transaction(async (tx) => { const current = await tx.admission.findUnique({ where: { id: Number(req.params.id) } }); if (!current || current.status !== 'ADMITTED') throw Object.assign(new Error('Active admission not found'), { status: 404 }); const updated = await tx.admission.update({ where: { id: current.id }, data: { status: 'DISCHARGED', dischargeDate: new Date(), dischargeSummary: req.body.dischargeSummary, finalDiagnosis: req.body.finalDiagnosis } }); await tx.bed.update({ where: { id: current.bedId }, data: { status: 'AVAILABLE' } }); return updated; }); res.json(admission); } catch (error) { res.status(error.status || 500).json({ message: error.status ? error.message : 'Unable to discharge patient' }); } });

app.get('/api/reports/summary', authenticate, authorize('ADMIN'), async (_req, res, next) => { try { const [patients, appointments, sales, invoices] = await Promise.all([prisma.patient.count(), prisma.appointment.count(), prisma.pharmacySale.aggregate({ _sum: { total: true } }), prisma.invoice.aggregate({ _sum: { total: true, paid: true } })]); res.json({ patients, appointments, pharmacyRevenue: sales._sum.total || 0, billed: invoices._sum.total || 0, collected: invoices._sum.paid || 0 }); } catch (error) { next(error); } });

app.post('/api/users', authenticate, authorize('ADMIN'), [body('name').trim().notEmpty(), body('username').optional().trim().isLength({ min: 3 }).withMessage('Username must be at least 3 characters'), body('email').isEmail().normalizeEmail(), body('password').isLength({ min: 12 }).withMessage('Password must be at least 12 characters'), body('role').isIn(['ADMIN', 'DOCTOR', 'RECEPTION', 'LAB', 'PHARMACY']).withMessage('Invalid role')], validate, async (req, res, next) => { try { const passwordHash = await bcrypt.hash(req.body.password, 12); const user = await prisma.user.create({ data: { name: req.body.name, username: req.body.username || undefined, email: req.body.email, passwordHash, role: req.body.role }, select: { id: true, name: true, username: true, email: true, role: true, status: true, createdAt: true } }); await audit(req.user.id, 'USER_CREATED', 'User', user.id); res.status(201).json(user); } catch (error) { if (error.code === 'P2002') return res.status(409).json({ message: 'Username or email already exists' }); next(error); } });
app.get('/api/users', authenticate, authorize('ADMIN'), async (_req, res, next) => { try { res.json(await prisma.user.findMany({ select: { id: true, name: true, email: true, role: true, status: true, createdAt: true }, orderBy: { createdAt: 'desc' } })); } catch (error) { next(error); } });
app.get('/api/audit', authenticate, authorize('ADMIN'), async (_req, res, next) => { try { res.json(await prisma.auditLog.findMany({ include: { user: { select: { name: true, email: true } } }, orderBy: { createdAt: 'desc' }, take: 100 })); } catch (error) { next(error); } });
app.use((_req, res) => res.status(404).json({ message: 'Route not found' }));
app.use((error, _req, res, _next) => { if (process.env.NODE_ENV !== 'production') console.error(error); const status = error.code === 'P2002' ? 409 : 500; res.status(status).json({ message: status === 409 ? 'A record with that value already exists' : 'Internal server error' }); });
