import { useEffect, useState } from 'react';
import { Activity, ArrowRight, BarChart3, BedDouble, CalendarDays, ChevronDown, ClipboardList, Eye, EyeOff, FileText, FlaskConical, LayoutDashboard, LogOut, Menu, Package, Plus, Search, Settings, ShieldCheck, Stethoscope, UserRound, Users } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { api, auth } from './services/api';
import PatientRegistration from './components/PatientRegistration';
import ReferenceAgents from './components/ReferenceAgents';
import Pharmacy from './components/Pharmacy';
import AdmissionConversion from './components/AdmissionConversion';
import RoomManagement from './components/RoomManagement';
import DischargeToOutpatient from './components/DischargeToOutpatient';
import RegistrationModes from './components/RegistrationModes';
import './styles.css';
import './sidebar.css';
import './responsive-shell.css';

const roles = { ADMIN: 'Admin', DOCTOR: 'Doctor', RECEPTION: 'Reception', LAB: 'Laboratory', PHARMACY: 'Pharmacy' };
const menu = {
  ADMIN: [['dashboard', 'Dashboard', LayoutDashboard], ['registration', 'Patient Registration', UserRound], ['admission', 'Room & Bed Management', BedDouble], ['patients', 'Patient Records', Users], ['appointments', 'Appointments', CalendarDays], ['referenceAgents', 'Reference Agents', Users], ['pharmacy', 'Pharmacy & Billing', Package], ['laboratory', 'Diagnostics', FlaskConical], ['users', 'User Management', ShieldCheck], ['reports', 'Reports & Analytics', BarChart3], ['account', 'Account & Settings', Settings]],
  DOCTOR: [['dashboard', 'Dashboard', LayoutDashboard], ['patients', 'Patient Records', Users], ['appointments', 'Appointments', CalendarDays], ['laboratory', 'Diagnostics & Results', FlaskConical], ['prescriptions', 'Prescriptions', FileText]],
  RECEPTION: [['dashboard', 'Dashboard', LayoutDashboard], ['registration', 'Registration Forms', UserRound], ['inpatient', 'Convert Outpatient to Inpatient', ClipboardList], ['discharge', 'Inpatient to Outpatient', LogOut], ['outpatient', 'Outpatient', UserRound], ['patients', 'Patient Records', Users], ['appointments', 'Appointments', CalendarDays], ['referenceAgents', 'Reference Agents', Users], ['billing', 'Billing & Collections', FileText], ['pharmacy', 'Pharmacy Billing', Package]],
  LAB: [['dashboard', 'Dashboard', LayoutDashboard], ['laboratory', 'Lab Orders & Results', FlaskConical], ['reports', 'Lab Reports', FileText]],
  PHARMACY: [['dashboard', 'Dashboard', LayoutDashboard], ['pharmacy', 'Pharmacy Billing', Package], ['patients', 'Patient Search', Users]]
};
const targetPage = { inpatient: 'admission', discharge: 'discharge', outpatient: 'registration', billing: 'pharmacy', reports: 'laboratory', prescriptions: 'laboratory', account: 'users' };

function Login({ onLogin }) { const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const result = await auth.login(identifier, password); localStorage.setItem('hms_token', result.token); localStorage.setItem('hms_user', JSON.stringify(result.user)); onLogin(result.user); } catch (cause) { setError(cause.message); } finally { setBusy(false); } } return <main className="login-page"><section className="login-art"><div className="brand-mark"><Activity size={22} /> CareDesk</div><div><p className="eyebrow">LOCAL HOSPITAL OPERATIONS</p><h1>One calm place<br />for better care.</h1><p className="muted">Registration, clinical work, diagnostics, pharmacy, and billing in one workspace.</p></div></section><section className="login-panel"><div className="login-card"><div className="mobile-brand brand-mark"><Activity size={22} /> CareDesk</div><p className="eyebrow">WELCOME BACK</p><h2>Sign in to HMS</h2><p className="muted">Use your username or assigned email.</p><form onSubmit={submit}><label>Username or email<input value={identifier} onChange={(event) => setIdentifier(event.target.value)} autoComplete="username" required /></label><label>Password<div className="password-field"><input value={password} onChange={(event) => setPassword(event.target.value)} type={visible ? 'text' : 'password'} autoComplete="current-password" required /><button className="password-toggle" type="button" aria-label={visible ? 'Hide password' : 'Show password'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>{error && <div className="alert error">{error}</div>}<button className="primary full" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'} <ArrowRight size={17} /></button></form></div></section></main>; }

function App() { const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('hms_user') || 'null')); const [page, setPage] = useState('dashboard'); const [open, setOpen] = useState(false); if (!user) return <Login onLogin={setUser} />; const items = menu[user.role] || menu.RECEPTION; const label = items.find(([key]) => key === page)?.[1] || 'Dashboard'; function navigate(key) { setPage(targetPage[key] || key); setOpen(false); } function logout() { localStorage.clear(); setUser(null); } return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand-mark"><Activity size={21} /> CareDesk</div><div className="workspace-label">HMS WORKSPACE</div><nav>{items.map(([key, text, Icon]) => <button className={page === (targetPage[key] || key) ? 'nav-item active' : 'nav-item'} key={key} onClick={() => navigate(key)}><Icon size={17} />{text}</button>)}</nav><div className="sidebar-bottom"><div className="user-mini"><div className="avatar">{user.name?.[0]}</div><div><strong>{user.name}</strong><small>{roles[user.role]}</small></div></div><button className="nav-item" onClick={logout}><LogOut size={17} />Sign out</button></div></aside><div className="main"><header className="topbar"><button className="icon-button menu" onClick={() => setOpen(!open)}><Menu size={21} /></button><div><p className="date-line">Hospital Management System</p><h1>{label}</h1></div><div className="top-actions"><span className="status-dot">System online</span><div className="avatar">{user.name?.[0]}</div></div></header><div className="content">{page === 'dashboard' && <Dashboard user={user} navigate={navigate} />}{page === 'registration' && <RegistrationModes />}{page === 'admission' && (user.role === 'ADMIN' ? <RoomManagement /> : <AdmissionConversion />)}{page === 'discharge' && <DischargeToOutpatient />}{page === 'patients' && <Patients />}{page === 'appointments' && <Appointments />}{page === 'pharmacy' && <Pharmacy user={user} />}{page === 'laboratory' && <Laboratory />}{page === 'referenceAgents' && <ReferenceAgents user={user} />}{page === 'users' && <UsersPage />}{['reports', 'prescriptions'].includes(page) && <Laboratory />}</div></div></div>; }

function Dashboard({ user, navigate }) { const [stats, setStats] = useState(null); useEffect(() => { api('/dashboard').then(setStats).catch(() => {}); }, []); return <><div className="welcome-row"><div><p className="eyebrow">{roles[user.role]} DASHBOARD</p><p className="lede">Keep today moving with a clear view of the care queue.</p></div><button className="primary" onClick={() => navigate(user.role === 'RECEPTION' ? 'registration' : 'appointments')}><Plus size={17} /> New activity</button></div><div className="stat-grid">{[['Patients', stats?.patients ?? '--', Users], ["Today's visits", stats?.appointments ?? '--', CalendarDays], ['Active doctors', stats?.doctors ?? '--', Stethoscope], ['Pending lab work', stats?.pendingLabs ?? '--', FlaskConical]].map(([name, value, Icon]) => <div className="stat-card" key={name}><div className="stat-icon"><Icon size={19} /></div><div><span>{name}</span><strong>{value}</strong><small>Live from SQLite</small></div></div>)}</div><section className="panel queue"><div className="section-heading"><div><p className="eyebrow">HMS FLOW</p><h2>Today at a glance</h2></div><span className="live-pill"><i /> Live</span></div><div className="queue-list"><div><span className="queue-number">01</span><div><strong>Registration desk</strong><p>Register patient, visit, guardian, and medical details</p></div><ArrowRight size={18} /></div><div><span className="queue-number">02</span><div><strong>Clinical journey</strong><p>Appointment, consultation, diagnostics, prescription</p></div><ArrowRight size={18} /></div><div><span className="queue-number">03</span><div><strong>Revenue desk</strong><p>Billing, pharmacy sales, payments, and collections</p></div><ArrowRight size={18} /></div></div></section></>; }

function Patients() { const [items, setItems] = useState([]); const [search, setSearch] = useState(''); async function load() { setItems(await api(`/patients?search=${encodeURIComponent(search)}`)); } useEffect(() => { load().catch(() => {}); }, []); return <section className="panel table-panel"><div className="page-toolbar compact"><div><p className="eyebrow">PATIENT RECORDS</p><p className="lede">Search by patient number, name, mobile, or email.</p></div></div><div className="table-toolbar"><div className="search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Search patient records" /></div><button className="secondary" onClick={load}>Search</button></div><table><thead><tr><th>Patient</th><th>Patient number</th><th>Mobile</th><th>Gender</th><th>Registered</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.firstName} {item.lastName || ''}</strong><small>{item.email || 'No email'}</small></td><td>{item.patientNumber}</td><td>{item.mobile}</td><td><span className="tag">{item.gender}</span></td><td>{new Date(item.createdAt).toLocaleDateString()}</td></tr>)}{!items.length && <tr><td colSpan="5" className="empty">No patient records found.</td></tr>}</tbody></table></section>; }

function Appointments() { const [items, setItems] = useState([]); useEffect(() => { api('/appointments').then(setItems).catch(() => {}); }, []); return <section className="panel table-panel"><div className="page-toolbar compact"><div><p className="eyebrow">APPOINTMENTS</p><p className="lede">The live appointment queue from the backend.</p></div></div><table><thead><tr><th>Patient</th><th>Doctor</th><th>Date</th><th>Time</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.patient.firstName} {item.patient.lastName || ''}</strong><small>{item.patient.patientNumber}</small></td><td>{item.doctor.name}</td><td>{new Date(item.appointmentDate).toLocaleDateString()}</td><td>{item.appointmentTime}</td><td><span className="status">{item.status.replace('_', ' ')}</span></td></tr>)}{!items.length && <tr><td colSpan="5" className="empty">No appointments found.</td></tr>}</tbody></table></section>; }

function LegacyPharmacy({ user }) { const [items, setItems] = useState([]); const [message, setMessage] = useState(''); useEffect(() => { api('/pharmacy/products').then(setItems).catch((error) => setMessage(error.message)); }, []); return <><div className="page-toolbar"><div><p className="eyebrow">{user.role === 'PHARMACY' ? 'PHARMACY BILLING' : 'PHARMACY CONTROL'}</p><p className="lede">Search stock and use the transactional billing API.</p></div>{user.role === 'ADMIN' && <span className="tag">Admin product control</span>}</div>{message && <div className="alert error">{message}</div>}<section className="product-grid">{items.map((product) => { const batch = product.batches[0]; return <article className="product-card" key={product.id}><div className="product-top"><div className="product-icon"><Package size={20} /></div><span className={batch?.quantity <= product.reorderLevel ? 'tag warning' : 'tag'}>{batch?.quantity <= product.reorderLevel ? 'Low stock' : 'In stock'}</span></div><h3>{product.name}</h3><p className="muted">{product.genericName || 'General medicine'} · Batch {batch?.batchNumber}</p><div className="product-meta"><span><strong>{batch?.quantity ?? 0}</strong> units</span><span>₹{batch?.sellingPrice ?? 0}</span></div></article>; })}</section></>; }

function Laboratory() { const [orders, setOrders] = useState([]); useEffect(() => { api('/lab/orders').then(setOrders).catch(() => {}); }, []); return <section className="panel table-panel"><div className="page-toolbar compact"><div><p className="eyebrow">DIAGNOSTICS</p><p className="lede">Lab orders, samples, and result status.</p></div></div><table><thead><tr><th>Patient</th><th>Tests</th><th>Ordered by</th><th>Status</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.patient.firstName} {order.patient.lastName || ''}</strong><small>{order.patient.patientNumber}</small></td><td>{order.items.map((item) => item.labTest.name).join(', ')}</td><td>{order.orderedBy.name}</td><td><span className="status">{order.status.replace('_', ' ')}</span></td></tr>)}{!orders.length && <tr><td colSpan="4" className="empty">No lab orders found.</td></tr>}</tbody></table></section>; }

function UsersPage() { const [users, setUsers] = useState([]); const [message, setMessage] = useState(''); const [form, setForm] = useState({ name: '', username: '', email: '', password: '', role: 'DOCTOR' }); async function load() { setUsers(await api('/users')); } useEffect(() => { load().catch((error) => setMessage(error.message)); }, []); async function submit(event) { event.preventDefault(); try { await api('/users', { method: 'POST', body: JSON.stringify(form) }); setMessage('User created successfully.'); setForm({ name: '', username: '', email: '', password: '', role: 'DOCTOR' }); await load(); } catch (error) { setMessage(error.message); } } return <><form className="panel form-panel" onSubmit={submit}><div className="section-heading"><div><p className="eyebrow">ADMINISTRATION</p><h2>Create user and assign role</h2></div></div><div className="form-grid">{[['name','Full name','text'],['username','Username','text'],['email','Email','email'],['password','Password (12+ characters)','password']].map(([key,label,type]) => <label key={key}>{label}<input required value={form[key]} type={type} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label>Role<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option>ADMIN</option><option>DOCTOR</option><option>RECEPTION</option><option>LAB</option><option>PHARMACY</option></select></label></div><button className="primary"><Plus size={17} /> Create user</button>{message && <div className="alert">{message}</div>}</form><section className="panel table-panel"><table><thead><tr><th>Name</th><th>Username</th><th>Email</th><th>Role</th></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.username || '—'}</td><td>{item.email}</td><td><span className="tag">{roles[item.role]}</span></td></tr>)}</tbody></table></section></>; }

createRoot(document.getElementById('root')).render(<App />);
